async function allData(){const out={};for(const s of STORES)out[s]=await getAll(s);return out}
function habitDaySummary(h,records,date){const rs=records.filter(r=>r.habitId===h.id&&r.date===date).sort((a,b)=>(a.time||'').localeCompare(b.time||''));let value=0,done=false;if(h.type==='boolean'){value=rs.length;done=rs.length>0}else if(h.type==='count'){value=rs.length;done=h.target?value>=Number(h.target):rs.length>0}else if(h.type==='measurement'){value=rs.length?Number(rs[rs.length-1].value||0):0;done=rs.length>0}else{value=rs.reduce((a,r)=>a+Number(r.value||0),0);done=h.target?value>=Number(h.target):rs.length>0}return{records:rs,value,done}}
function dayCompletion(habits,records,date){const active=habits.filter(h=>!h.paused);if(!active.length)return 0;return active.filter(h=>habitDaySummary(h,records,date).done).length/active.length}
function scheduleLabel(h){if(h.scheduleType==='recommended'&&h.startTime)return`推荐 ${h.startTime}`;if(h.scheduleType==='window'&&h.startTime)return`${h.startTime}${h.endTime?'–'+h.endTime:''}`;return'全天'}
function habitSummaryText(h,sum){if(h.type==='boolean')return sum.done?'已完成':'未完成';if(h.type==='count')return`${sum.value}${h.target?` / ${h.target}`:''} 次`;if(h.type==='measurement')return sum.done?`${sum.value} ${h.unit||''}`:'未记录';return`${sum.value}${h.target?` / ${h.target}`:''} ${h.unit||''}`}
function descendants(folderId,folders){const ids=[folderId];for(const c of folders.filter(f=>f.parentId===folderId))ids.push(...descendants(c.id,folders));return ids}
function folderHabitList(folderId,folders,habits){const ids=new Set(descendants(folderId,folders));return habits.filter(h=>ids.has(h.folderId))}
function folderPath(folderId,folders){const names=[];let cur=folders.find(f=>f.id===folderId);const seen=new Set();while(cur&&!seen.has(cur.id)){seen.add(cur.id);names.unshift(`${cur.emoji||'📁'} ${cur.name}`);cur=folders.find(f=>f.id===cur.parentId)}return names.join(' / ')}
function folderOptions(folders,selected='',excludeId=null){let html='<option value="">未归档</option>';const walk=(parentId,depth)=>{folders.filter(f=>(f.parentId||null)===(parentId||null)&&f.id!==excludeId).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN')).forEach(f=>{html+=`<option value="${f.id}" ${f.id===selected?'selected':''}>${'　'.repeat(depth)}${esc(f.emoji||'📁')} ${esc(f.name)}</option>`;walk(f.id,depth+1)})};walk(null,0);return html}
function normalizedPercent(items,key='weight'){if(!items.length)return[];const raw=items.map(x=>x[key]);if(raw.every(v=>v==null||v===''))return items.map(()=>100/items.length);const vals=raw.map(v=>Math.max(0,Number(v)||0));const sum=vals.reduce((a,b)=>a+b,0);if(sum<=0)return items.map(()=>100/items.length);return vals.map(v=>v/sum*100)}
function periodRange(period){const end=new Date();let start=new Date(end);if(period==='day')start=new Date(end.getFullYear(),end.getMonth(),end.getDate());else if(period==='week'){const day=(end.getDay()+6)%7;start=new Date(end.getFullYear(),end.getMonth(),end.getDate()-day)}else if(period==='month')start=new Date(end.getFullYear(),end.getMonth(),1);else if(period==='year')start=new Date(end.getFullYear(),0,1);else{start=new Date(end);start.setDate(start.getDate()-29)}return[localISO(start),localISO(end)]}
