async function saveHabit(e){e.preventDefault();const f=e.currentTarget,id=f.habitId.value||uid(),old=f.habitId.value?await getOne('habits',id):null;await put('habits',{...(old||{}),id,name:f.name.value.trim(),emoji:f.emoji.value.trim()||'✅',folderId:f.folderId.value||null,type:f.type.value,target:f.target.value===''?null:Number(f.target.value),unit:f.unit.value.trim(),scheduleType:f.scheduleType.value,startTime:f.startTime.value,endTime:f.endTime.value,paused:f.paused.checked,goalId:null,krId:null});closeDialog('habitDialog');render()}
async function saveRecord(e){e.preventDefault();const f=e.currentTarget,h=await getOne('habits',f.habitId.value);if(!h)return;const id=f.recordId.value||uid();let value=1;if(!['boolean','count'].includes(h.type))value=Number(f.querySelector('[name="value"]')?.value||0);const old=f.recordId.value?await getOne('records',id):null;await put('records',{...(old||{}),id,habitId:h.id,date:f.date.value,time:f.time.value,note:f.note.value.trim(),value,updatedAt:new Date().toISOString()});closeDialog('recordDialog');render()}
async function saveGoal(e){e.preventDefault();const f=e.currentTarget,id=f.goalId.value||uid(),old=f.goalId.value?await getOne('goals',id):null;await put('goals',{...(old||{}),id,name:f.name.value.trim(),emoji:f.emoji.value.trim()||'🎯',description:f.description.value.trim()});closeDialog('goalDialog');render()}
async function saveKR(e){e.preventDefault();const f=e.currentTarget,id=f.krId.value||uid(),old=f.krId.value?await getOne('krs',id):null;await put('krs',{...(old||{}),id,goalId:f.goalId.value,name:f.name.value.trim(),metricType:f.metricType.value,period:f.period.value,startValue:Number(f.startValue.value||0),targetValue:Number(f.targetValue.value||0),currentValue:Number(f.currentValue.value||0),unit:f.unit.value.trim(),metricWeight:clamp(Number(f.metricWeight.value||80),0,100),objectiveWeight:old?.objectiveWeight??null,habitLinks:Array.isArray(old?.habitLinks)?old.habitLinks:[]});closeDialog('krDialog');render()}
async function saveFolder(e){e.preventDefault();const f=e.currentTarget,id=f.folderId.value||uid(),old=f.folderId.value?await getOne('folders',id):null;await put('folders',{...(old||{}),id,name:f.name.value.trim(),emoji:f.emoji.value.trim()||'📁',parentId:f.parentId.value||null});closeDialog('folderDialog');render()}
async function deleteHabit(){const id=$('#habitForm').habitId.value;if(!id||!confirm('删除这个打卡任务？历史记录也会一起删除。'))return;for(const r of (await getAll('records')).filter(r=>r.habitId===id))await del('records',r.id);for(const k of await getAll('krs')){const links=(k.habitLinks||[]).filter(l=>l.habitId!==id);if(links.length!==(k.habitLinks||[]).length)await put('krs',{...k,habitLinks:links})}await del('habits',id);closeDialog('habitDialog');render()}
async function deleteRecord(){const id=$('#recordForm').recordId.value;if(!id||!confirm('删除这条记录？'))return;await del('records',id);closeDialog('recordDialog');render()}
async function deleteGoal(){const id=$('#goalForm').goalId.value;if(!id||!confirm('删除这个 Objective？其下 KR 会一起删除，打卡任务本身不会删除。'))return;for(const k of (await getAll('krs')).filter(k=>k.goalId===id))await del('krs',k.id);await del('goals',id);closeDialog('goalDialog');render()}
async function deleteKR(){const id=$('#krForm').krId.value;if(!id||!confirm('删除这个 KR？关联任务不会删除。'))return;await del('krs',id);closeDialog('krDialog');render()}
async function deleteFolder(){const id=$('#folderForm').folderId.value;if(!id)return;const folders=await getAll('folders');if(folders.some(f=>f.parentId===id)){alert('这个文件夹下面还有子文件夹，请先移动或删除子文件夹。');return}if(!confirm('删除这个文件夹？里面的任务会移到“未归档”。'))return;for(const h of (await getAll('habits')).filter(h=>h.folderId===id))await put('habits',{...h,folderId:null});await del('folders',id);closeDialog('folderDialog');render()}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function linksForHabit(habitId,krs){return krs.filter(k=>(k.habitLinks||[]).some(l=>l.habitId===habitId))}
async function exportCSV(){const[records,habits,folders,goals,krs]=await Promise.all([getAll('records'),getAll('habits'),getAll('folders'),getAll('goals'),getAll('krs')]);const rows=[['日期','时间','文件夹','Objective','KR','任务','类型','数值','单位','备注']];for(const r of records.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))){const h=habits.find(x=>x.id===r.habitId);if(!h)continue;const linked=linksForHabit(h.id,krs),goalNames=[...new Set(linked.map(k=>goals.find(g=>g.id===k.goalId)?.name).filter(Boolean))].join(' | '),krNames=linked.map(k=>k.name).join(' | ');rows.push([r.date,r.time||'',folderPath(h.folderId,folders),goalNames,krNames,h.name,h.type,r.value,h.unit||'',r.note||''])}const csv='\ufeff'+rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),`Corntrack_${todayISO()}.csv`)}
async function exportExcel(){const[records,habits,folders,goals,krs]=await Promise.all([getAll('records'),getAll('habits'),getAll('folders'),getAll('goals'),getAll('krs')]);let body='<table><tr><th>日期</th><th>时间</th><th>文件夹</th><th>Objective</th><th>KR</th><th>任务</th><th>类型</th><th>数值</th><th>单位</th><th>备注</th></tr>';for(const r of records){const h=habits.find(x=>x.id===r.habitId);if(!h)continue;const linked=linksForHabit(h.id,krs),goalNames=[...new Set(linked.map(k=>goals.find(g=>g.id===k.goalId)?.name).filter(Boolean))].join(' | '),krNames=linked.map(k=>k.name).join(' | ');body+=`<tr><td>${esc(r.date)}</td><td>${esc(r.time||'')}</td><td>${esc(folderPath(h.folderId,folders))}</td><td>${esc(goalNames)}</td><td>${esc(krNames)}</td><td>${esc(h.name)}</td><td>${esc(h.type)}</td><td>${esc(r.value)}</td><td>${esc(h.unit||'')}</td><td>${esc(r.note||'')}</td></tr>`}body+='</table>';downloadBlob(new Blob(['\ufeff<html><meta charset="UTF-8"><body>'+body+'</body></html>'],{type:'application/vnd.ms-excel'}),`Corntrack_${todayISO()}.xls`)}
async function exportJSON(){const data=await allData();data.exportedAt=new Date().toISOString();await put('meta',{id:'lastBackup',value:new Date().toLocaleString('zh-CN')});downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`Corntrack_Backup_${todayISO()}.json`);if(state.tab==='data')renderData()}
async function restoreJSON(file){try{const data=JSON.parse(await file.text());if(!STORES.every(s=>Array.isArray(data[s])))throw new Error('备份结构不完整');if(!confirm('恢复备份会覆盖当前全部本地数据。继续吗？'))return;for(const s of STORES){await clearStore(s);for(const item of data[s])await put(s,item)}await migrateV4();alert('恢复完成');render()}catch(err){alert('恢复失败：'+err.message)}}
function wireEvents(){$$('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});$('#quickAddBtn').onclick=()=>{if(state.tab==='goals')openGoal();else openHabitEdit()};$$('[data-close]').forEach(b=>b.onclick=()=>closeDialog(b.dataset.close));$('#closeDayDialog').onclick=()=>closeDialog('dayDialog');$('#doneDayDialog').onclick=()=>closeDialog('dayDialog');$('#habitForm').addEventListener('submit',saveHabit);$('#recordForm').addEventListener('submit',saveRecord);$('#goalForm').addEventListener('submit',saveGoal);$('#krForm').addEventListener('submit',saveKR);$('#folderForm').addEventListener('submit',saveFolder);$('#deleteHabitBtn').onclick=deleteHabit;$('#deleteRecordBtn').onclick=deleteRecord;$('#deleteGoalBtn').onclick=deleteGoal;$('#deleteKrBtn').onclick=deleteKR;$('#deleteFolderBtn').onclick=deleteFolder;$('#equalWeightBtn').onclick=equalizeCurrentWeights;$('#saveWeightBtn').onclick=saveWeights;$('#restoreInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)restoreJSON(f);e.target.value=''});$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}))}
(async()=>{try{await openDB();await seed();await migrateV4();wireEvents();await render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(err){console.error(err);document.body.innerHTML=`<div style="padding:30px;font-family:-apple-system">启动失败：${esc(err.message)}</div>`}})();
