function recordsInRange(records,start,end,habitIds=null){return records.filter(r=>r.date>=start&&r.date<=end&&(!habitIds||habitIds.has(r.habitId)))}
function compatibleWithKR(kr,h){if(kr.metricType==='count')return true;if(kr.metricType==='duration')return h.type==='duration';if(kr.metricType==='quantity')return h.type==='quantity'&&(!kr.unit||!h.unit||kr.unit===h.unit);if(kr.metricType==='measurement')return h.type==='measurement'&&(!kr.unit||!h.unit||kr.unit===h.unit);return false}
function metricValueForKR(kr,habits,records){if(kr.metricType==='manual')return Number(kr.currentValue||0);const links=kr.habitLinks||[];const ids=new Set(links.map(x=>x.habitId));const[start,end]=periodRange(kr.period);const rs=recordsInRange(records,start,end,ids);if(kr.metricType==='count')return rs.length;if(kr.metricType==='duration'){const valid=new Set(habits.filter(h=>ids.has(h.id)&&h.type==='duration').map(h=>h.id));return rs.filter(r=>valid.has(r.habitId)).reduce((a,r)=>a+Number(r.value||0),0)}if(kr.metricType==='quantity'){const valid=new Set(habits.filter(h=>ids.has(h.id)&&h.type==='quantity'&&(!kr.unit||!h.unit||kr.unit===h.unit)).map(h=>h.id));return rs.filter(r=>valid.has(r.habitId)).reduce((a,r)=>a+Number(r.value||0),0)}if(kr.metricType==='measurement'){const valid=new Set(habits.filter(h=>ids.has(h.id)&&h.type==='measurement'&&(!kr.unit||!h.unit||kr.unit===h.unit)).map(h=>h.id));const found=rs.filter(r=>valid.has(r.habitId)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));return found.length?Number(found[found.length-1].value||0):Number(kr.currentValue||kr.startValue||0)}return Number(kr.currentValue||0)}
function metricProgressForKR(kr,current){const s=Number(kr.startValue||0),t=Number(kr.targetValue||0),c=Number(current||0);if(kr.metricType==='measurement'||kr.metricType==='manual'){if(t===s)return c===t?1:0;return clamp((c-s)/(t-s),0,1)}return t>0?clamp(c/t,0,1):0}
function datesBetween(start,end){const out=[];const d=new Date(`${start}T12:00:00`),e=new Date(`${end}T12:00:00`);while(d<=e){out.push(localISO(d));d.setDate(d.getDate()+1)}return out}
function habitExecutionProgress(h,records,start,end){const dates=datesBetween(start,end);if(!dates.length)return 0;let done=0;for(const d of dates)if(habitDaySummary(h,records,d).done)done++;return done/dates.length}
function krStats(kr,habits,records){const links=(kr.habitLinks||[]).filter(l=>habits.some(h=>h.id===l.habitId));const current=metricValueForKR(kr,habits,records);const metricProgress=metricProgressForKR(kr,current);const[start,end]=periodRange(kr.period);let actionProgress=0;if(links.length){const weights=normalizedPercent(links);actionProgress=links.reduce((sum,l,i)=>{const h=habits.find(x=>x.id===l.habitId);return sum+(weights[i]/100)*habitExecutionProgress(h,records,start,end)},0)}const mw=clamp(Number(kr.metricWeight??80),0,100)/100;const total=links.length?metricProgress*mw+actionProgress*(1-mw):metricProgress;return{current,metricProgress,actionProgress,total,start,end}}
function goalStats(goal,krs,habits,records){const ks=krs.filter(k=>k.goalId===goal.id);if(!ks.length)return{total:0,weights:[]};const weights=normalizedPercent(ks,'objectiveWeight');const total=ks.reduce((s,k,i)=>s+(weights[i]/100)*krStats(k,habits,records).total,0);return{total,weights}}
function metricTypeLabel(t){return({count:'次数',duration:'时长',quantity:'数量',measurement:'数值',manual:'手动'})[t]||t}
function periodLabel(p){return({day:'每日',week:'每周',month:'每月',year:'每年',cumulative:'累计'})[p]||p}
